### ISSUE TITLE
java.lang.NoSuchMethodError while executing LandCoverClassificationAlgorithm

### ISSUE THREAD

**Issue by arnevogt** [WaCoDiS/javaps-wacodis-backend#2]
java.lang.NoSuchMethodError raised while executing _de.hsbo.wacodis.land_cover_classification_ (LandCoverClassificationAlgorithm). The error is raised when trying to create a Docker Container  for the processing tool using [_docker-java_](https://github.com/docker-java/docker-java/tree/3.0.x).

### Preconditions:
-  running [_javaPS_](https://github.com/WaCoDiS/javaPS/tree/wacodis/eo-hackathon)  in Docker Container (Image: _tomcat:9.0.16-jre8_)
-  docker-java uses Docker Host _unix:///var/run/docker.sock_ (configure in _landcoverclassification.properties_)
-  branch: _feature/land-classification_

### Possible Cause
Built WAR-archive of javaPS-Webapp contains [_Apache Commons IO Version 2.1_](https://commons.apache.org/proper/commons-io/javadocs/api-2.1/index.html) (_WEB_INF/lib/commons.io-2.1.jar_). Method _org.apache.commons.io.IOUtils.readFully_ is not yet available in version 2.1. A transitive dependency requires a higher version of Apache Commons IO.

### Log Files
[wacodis_tomcat_wps_log.txt](https://github.com/WaCoDiS/javaps-wacodis-backend/files/3029678/wacodis_tomcat_wps_log2.txt)

`java.lang.NoSuchMethodError: org.apache.commons.io.IOUtils.readFully(Ljava/io/InputStream;[B)V
	at com.github.dockerjava.jaxrs.filter.ResponseStatusExceptionFilter.getBodyAsMessage(ResponseStatusExceptionFilter.java:66) ~[docker-java-3.0.14.jar:?]
	at com.github.dockerjava.jaxrs.filter.ResponseStatusExceptionFilter.filter(ResponseStatusExceptionFilter.java:47) ~[docker-java-3.0.14.jar:?]
	at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:109) ~[jersey-client-2.28.jar:?]
	at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:97) ~[jersey-client-2.28.jar:?]
	at org.glassfish.jersey.process.internal.Stages.process(Stages.java:147) ~[jersey-common-2.28.jar:?]
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:259) ~[jersey-client-2.28.jar:?]
	at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$1
[...]`

**Comment by arnevogt** [comment]
### solution approach
Use higher version of _Apache Commons IO_.
The error did not occur after manually changing _WEB-INF\lib\commons.io-2.1.jar_ to _commons.io-2.6.jar_.

To fix this issue, the project configuration should be changed so that a higher version of _Apache Commons IO_ is included in the resulting WAR archive.

**Comment by arnevogt** [comment]
issue resolved with commit [573061c](https://github.com/WaCoDiS/javaPS/commit/573061cb18f4d9aed79642c403343c310daf3157) to [javaPS wacodis/eo-hackathon](https://github.com/WaCoDiS/javaPS/tree/wacodis/eo-hackathon) ,
excludes outdated versions of _Apache Commons IO_, enforces at least Version 2.2 of _Apache Commons IO_.

Use javaPS including commit [573061c](https://github.com/WaCoDiS/javaPS/commit/573061cb18f4d9aed79642c403343c310daf3157) to deploy _javaps-wacodis-backend_
