### ISSUE TITLE
unable to run develop branch

### ISSUE THREAD

**Issue by arnevogt** [WaCoDiS/javaps-wacodis-backend#4]
Running [java-ps](https://github.com/WaCoDiS/javaPS/tree/develop) with _javaps-wacodis-backend_ (develop branch) registered evokes exception.

This issue exist since commit c036cbd54fa74c878e3cb8c9e438c589ba92e86a.
Removing dependency _s1tbx-op-utilities_ solves the issue.

Possibly this is rather a issue with _javaps_ than _javaps-wacodis-backend_.

`ERROR org.springframework.web.servlet.DispatcherServlet - Context initialization failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.n52.iceland.util.http.HttpUtils#0': Unsatisfied dependency expressed through method 'setResponseWriterRepository' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'responseWriterRepository': Unsatisfied dependency expressed through field 'componentFactories'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'serviceResponseWriterFactory' defined in URL [jar:file:/C:/Users/Arne/.m2/repository/org/n52/wps/iceland-stream/1.4.0-SNAPSHOT/iceland-stream-1.4.0-SNAPSHOT.jar!/components/components.xml]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'streamWriterRepository' defined in URL [jar:file:/C:/Users/Arne/.m2/repository/org/n52/wps/iceland-stream/1.4.0-SNAPSHOT/iceland-stream-1.4.0-SNAPSHOT.jar!/components/components.xml]: Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanInitializationException: Couldn't counstruct bean streamWriterRepository; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'documentXmlStreamWriter' defined in URL [jar:file:/C:/Users/Arne/.m2/repository/org/n52/wps/iceland-stream/1.4.0-SNAPSHOT/iceland-stream-1.4.0-SNAPSHOT.jar!/components/components.xml]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'elementXmlStreamWriterRepository' defined in URL [jar:file:/C:/Users/Arne/.m2/repository/org/n52/wps/iceland-stream/1.4.0-SNAPSHOT/iceland-stream-1.4.0-SNAPSHOT.jar!/components/components.xml]: Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanInitializationException: Couldn't counstruct bean elementXmlStreamWriterRepository; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'wpsWriter' defined in URL [jar:file:/C:/Users/Arne/.m2/repository/org/n52/wps/xml/1.4.0-SNAPSHOT/xml-1.4.0-SNAPSHOT.jar!/components/components.xml]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.n52.javaps.service.xml.WPSWriter]: Constructor threw exception; nested exception is java.lang.IllegalArgumentException: Unrecognized property 'escapeCharacters'
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredMethodElement.inject(AutowiredAnnotationBeanPostProcessor.java:676) ~[spring-beans-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90) ~[spring-beans-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:374) ~[spring-beans-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1378) ~[spring-beans-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:575) ~[spring-beans-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498) ~[spring-beans-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:846) ~[spring-beans-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:863) ~[spring-context-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546) ~[spring-context-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.configureAndRefreshWebApplicationContext(FrameworkServlet.java:701) ~[spring-webmvc-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:667) ~[spring-webmvc-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:715) ~[spring-webmvc-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.initWebApplicationContext(FrameworkServlet.java:590) ~[spring-webmvc-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.initServletBean(FrameworkServlet.java:529) [spring-webmvc-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.web.servlet.HttpServletBean.init(HttpServletBean.java:169) [spring-webmvc-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at javax.servlet.GenericServlet.init(GenericServlet.java:244) [javax.servlet-api-3.1.0.jar:3.1.0]
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:621) [jetty-servlet-9.3.2.v20150730.jar:9.3.2.v20150730]
	at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:403) [jetty-servlet-9.3.2.v20150730.jar:9.3.2.v20150730]
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:873) [jetty-servlet-9.3.2.v20150730.jar:9.3.2.v20150730]
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:346) [jetty-servlet-9.3.2.v20150730.jar:9.3.2.v20150730]
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1368) [jetty-webapp-9.3.2.v20150730.jar:9.3.2.v20150730]
	at org.eclipse.jetty.maven.plugin.JettyWebAppContext.startWebapp(JettyWebAppContext.java:320) [jetty-maven-plugin-9.3.2.v20150730.jar:9.3.2.v20150730]
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1335) [jetty-webapp-9.3.2.v20150730.jar:9.3.2.v20150730]
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:735) [jetty-server-9.3.2.v20150730.jar:9.3.2.v20150730]
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:259) [jetty-servlet-9.3.2.v20150730.jar:9.3.2.v20150730]
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:511) [jetty-webapp-9.3.2.v20150730.jar:9.3.2.v20150730]
	at org.eclipse.jetty.maven.plugin.JettyWebAppContext.doStart(JettyWebAppContext.java:403) [jetty-maven-plugin-9.3.2.v20150730.jar:9.3.2.v20150730]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.3.2.v20150730.jar:9.3.2.v20150730]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132) [jetty-util-9.3.2.v20150730.jar:9.3.2.v20150730]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114) [jetty-util-9.3.2.v20150730.jar:9.3.2.v20150730]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61) [jetty-server-9.3.2.v20150730.jar:9.3.2.v20150730]
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:161) [jetty-server-9.3.2.v20150730.jar:9.3.2.v20150730]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.3.2.v20150730.jar:9.3.2.v20150730]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132) [jetty-util-9.3.2.v20150730.jar:9.3.2.v20150730]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114) [jetty-util-9.3.2.v20150730.jar:9.3.2.v20150730]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61) [jetty-server-9.3.2.v20150730.jar:9.3.2.v20150730]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.3.2.v20150730.jar:9.3.2.v20150730]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132) [jetty-util-9.3.2.v20150730.jar:9.3.2.v20150730]
	at org.eclipse.jetty.server.Server.start(Server.java:405) [jetty-server-9.3.2.v20150730.jar:9.3.2.v20150730]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:106) [jetty-util-9.3.2.v20150730.jar:9.3.2.v20150730]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61) [jetty-server-9.3.2.v20150730.jar:9.3.2.v20150730]
	at org.eclipse.jetty.server.Server.doStart(Server.java:372) [jetty-server-9.3.2.v20150730.jar:9.3.2.v20150730]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.3.2.v20150730.jar:9.3.2.v20150730]
	at org.eclipse.jetty.maven.plugin.AbstractJettyMojo.startJetty(AbstractJettyMojo.java:457) [jetty-maven-plugin-9.3.2.v20150730.jar:9.3.2.v20150730]
	at org.eclipse.jetty.maven.plugin.AbstractJettyMojo.execute(AbstractJettyMojo.java:328) [jetty-maven-plugin-9.3.2.v20150730.jar:9.3.2.v20150730]
	at org.eclipse.jetty.maven.plugin.JettyRunMojo.execute(JettyRunMojo.java:170) [jetty-maven-plugin-9.3.2.v20150730.jar:9.3.2.v20150730]
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137) [maven-core-3.6.0.jar:3.6.0]
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210) [maven-core-3.6.0.jar:3.6.0]
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156) [maven-core-3.6.0.jar:3.6.0]
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148) [maven-core-3.6.0.jar:3.6.0]
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117) [maven-core-3.6.0.jar:3.6.0]
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81) [maven-core-3.6.0.jar:3.6.0]
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56) [maven-core-3.6.0.jar:3.6.0]
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128) [maven-core-3.6.0.jar:3.6.0]
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305) [maven-core-3.6.0.jar:3.6.0]
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192) [maven-core-3.6.0.jar:3.6.0]
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105) [maven-core-3.6.0.jar:3.6.0]
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956) [maven-embedder-3.6.0.jar:3.6.0]
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288) [maven-embedder-3.6.0.jar:3.6.0]
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:192) [maven-embedder-3.6.0.jar:3.6.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_102]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_102]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_102]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_102]
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289) [plexus-classworlds-2.5.2.jar:?]
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229) [plexus-classworlds-2.5.2.jar:?]
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415) [plexus-classworlds-2.5.2.jar:?]
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356) [plexus-classworlds-2.5.2.jar:?]`

**Comment by SebaDro** [comment]
The _s1tbx-op-utilities_ provides another implementation of `XMLOutputFactory` than the one used and configured by the javaPS dependency `org.n52.arctic-sea.iceland` which causes the exception at runtime.  Placing a provider-configuration file in the resource directory _META-INF/services_ with `com.sun.xml.internal.stream.XMLOutputFactoryImpl` as implementation solves this issue. Therefore, 98794f7 should fix it.
